#!/usr/bin/env python3
import http.client
import urllib, os, glob, time

os.system('modprobe w1-gpio')
os.system('modprobe w1-therm')
base_dir = '/sys/bus/w1/devices/'
device_id = ['28-3c01d607acbc', '28-3c01d607c885', '28-3c01d607865f']

temp=[0,0,0,0,0,0,0,0]

def read_temp_raw():
    f = open(device_file, 'r')
    lines = f.readlines()
    f.close()
    return lines

def read_temp():
    lines = read_temp_raw()
    while lines[0].strip()[-3:] != 'YES':
        time.sleep(0.2)
        lines = read_temp_raw()
    equals_pos = lines[1].find('t=')
    if equals_pos != -1:
        temp_string = lines[1][equals_pos+2:]
        temp_c = float(temp_string) / 1000.0
        return temp_c

print(device_id)
for sensors in range (len(device_id)):
    device_file = base_dir + device_id[sensors] + '/w1_slave'
    temp[sensors] = read_temp()
    print(temp)

params = urllib.parse.urlencode({'key':'schlüssel hier einfügen', 'field1': temp[0], 'field2': temp[1], 'field3': temp[2], 'field4': temp[3], 'field5': temp[4], 'field6': temp[5], 'field7': temp[6], 'field8': temp[7]})
headers = {"Content-type": "application/x-www-form-urlencoded","Accept": "text/plain"}
conn = http.client.HTTPConnection("api.thingspeak.com:80")
conn.request("POST", "/update", params, headers)
response = conn.getresponse()
print (response.status, response.reason)
data = response.read()
